### ISSUE TITLE
Update package requirements for CDI branch?

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/TerriaMap#111]
I was building the `cdi` branch using the `selectWMSelevation` branch of `terriajs`, but now it's been merged into master: https://github.com/TerriaJS/terriajs/commit/a86f74f30370f2e41418176e1e7a57c01c71a7c3

So I changed my `TerriaMap` `cdi` branch `package.json` from
```
    "terriajs": "git://github.com/TerriaJS/terriajs#selectWmsElevation",
```
to
```
    "terriajs": "git://github.com/TerriaJS/terriajs",
```
but after building, something is clearly wrong:
![2016-10-12_9-55-20](https://cloud.githubusercontent.com/assets/1872600/19313298/fd7779bc-9063-11e6-8c88-43c5ed6e46b5.png)

I'm thinking that there are more package updates required than just this line?
https://github.com/TerriaJS/TerriaMap/blob/cdi/package.json#L58

**Comment by kring** [comment]
@rsignell-usgs I believe we resolve this today (it turned out to be an npm problem; removing node_modules and reinstalling fixed it), so I'm closing it.

**Comment by rsignell-usgs** [comment]
Indeed, we fixed it thusly:
```
* edit package.json to use master
* run npm install
* run gulp sync-terriajs-dependencies
* rm -rf node_modules
* npm install
* gulp
```
