### ISSUE TITLE
faq.html contains merge markers

### ISSUE THREAD

**Issue by meh9** [TerriaJS/TerriaMap#160]
There are some

```
>>>>>>> terriamap/master

=======

<<<<<<< HEAD
```

that have been left in the faq.html page.

**Comment by kring** [comment]
I don't see them @meh9?  https://github.com/TerriaJS/TerriaMap/blob/master/wwwroot/help/faq.html

**Comment by meh9** [comment]
Hmm, maybe they've been fixed then, they are on the live version:

http://map.terria.io/help/faq.html

**Comment by kring** [comment]
Oh ok, that's https://github.com/TerriaJS/terrarium, not this project.
