### ISSUE TITLE
Not install in windows 10

### ISSUE THREAD

**Issue by Chirag19** [TerriaJS/TerriaMap#189]
Can you provide step to step installation for windows-10

**Comment by steve9164** [comment]
You should be able to follow the steps [here](https://github.com/TerriaJS/TerriaJS#getting-started) on Windows 10 once you have NodeJS, NPM and Git installed (without the `sudo`).

**Comment by kring** [comment]
The best instructions can be found here:
http://terria.io/Documentation/guide/getting-started/
