### ISSUE TITLE
MapBox Vector Tile Support (PBF)

### ISSUE THREAD

**Issue by geospatialmapmashup** [TerriaJS/TerriaMap#190]
There is no catalog item for vector tiles

However, I see code for mapbox vector tiles as well as a tileserver in another repo.

I want to serve vector tiles i've created with MapBox Tippecanoe and have setup in TileServer-GL 
I know that with TileServer-GL i can serve a raster tile version of the vector tile (as long as I provide the style) and terriajs will load those.

**Comment by steve9164** [comment]
Hi @geospatialmapmashup. Currently we only use mapbox vector tiles for the "regionmapping" feature of TerriaJS.

Creating a CatalogItem built upon MapboxVectorTileImageryProvider.js would be the easiest way to add general mapbox vector tile rendering to TerriaJS.

**Comment by steve9164** [comment]
@geospatialmapmashup TerriaJS now has elementary support for rendering mapbox vector tiles as a catalog item. You need to provide a url to the tiles as well as a `minimumZoom` and `maximumNativeZoom` (the maximum zoom level that is available in the tileset). Styling is done by setting the `fillColor` and `lineColor`
