### ISSUE TITLE
gulp error

### ISSUE THREAD

**Issue by vladimircostas** [TerriaJS/TerriaMap#196]
I have no idea at the moment where is the problem with GULP .

I just tried to install terria on Ubuntu 16.04 node 6, and I get the following error:
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "gulp"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! terriajs-map@0.0.1 gulp: `gulp`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the terriajs-map@0.0.1 gulp script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the terriajs-map package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs terriajs-map
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls terriajs-map
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vladimir/TerriaMap/npm-debug.log

**Comment by kring** [comment]
Did you run `npm install` in the TerriaMap directory first? If so, it could be worth removing your `node_modules` directory and running it again.  You can also try `npm install -g gulp` and then run `gulp` directly instead of `npm run gulp`.

**Comment by vladimircostas** [comment]
Ok removing node_modules worked. Thanks a lot
