### ISSUE TITLE
How can I automatically Zoom To Extent?

### ISSUE THREAD

**Issue by jodiegardiner** [TerriaJS/TerriaMap#204]
I'm pretty green so maybe there's something obvious and simple but I'm having more trouble than I expected I would trying to automatically zoom to the extent.  

I found the zoomTo() which triggers it but can't figure out how to do it when the data loads.

**Comment by jodiegardiner** [comment]
I suspect it might not be simple otherwise it would surely be the default behaviour?

**Comment by kring** [comment]
@jodiegardiner you should be able to set `"zoomOnEnable": true` in the catalog item properties in your init file.  The only catch is if the catalog item is enabled during loading (i.e. `"isEnabled": true` is also in the init file), then the zoom won't happen automatically.  Does that solve your problem?

**Comment by jodiegardiner** [comment]
@kring Yes!  and also No!  I set `"zoomOnEnable": true` and if I manually add a data layer it works perfectly.  My use case is as a view in CKAN where a WMS layer is brought in from GeoServer then fed to Terria and for this layer, it does not automatically zoom (again, if I manually add the same data layer at this point, it does zoom).
