### ISSUE TITLE
How to build with local terriajs?

### ISSUE THREAD

**Issue by EricSoroos** [TerriaJS/TerriaMap#256]
I'm trying to build TerriaMap with a checkout of terriajs with some changes. 

The procedure so far is:

```
cd TerriaMap
npm install .
npm install grunt
npm install ../terriajs
npm run grunt build
...
[17:38:27] Starting 'build-app'...
You have two copies of terriajs-cesium, one in this application's node_modules
directory and the other in node_modules/terriajs/node_modules/terriajs-cesium.
This leads to strange problems, such as knockout observables not working.
Please verify that node_modules/terriajs-cesium is the correct version and
  rm -rf node_modules/terriajs/node_modules/terriajs-cesium
Also consider running:
  npm run gulp sync-terriajs-dependencies
to prevent this problem from recurring the next time you `npm install`.
[17:38:27] 'build-app' errored after 790 ms
```
Following the directions leads to dependency issues with terriajs-cesium, and hacking out cesium from terriajs leads to a cascade of other errors. This doesn't seem like a productive direction. 

What's the accepted way to build with a locally modified terriajs?

**Comment by kring** [comment]
Hi @EricSoroos, the instructions for building with a modified TerriaJS can be found here:
https://terria.io/Documentation/guide/contributing/development-environment/

If you check out the exact version of TerriaJS listed in TerriaMap's package.json, the instructions there should work unmodified. If you check out `master` of TerriaJS instead, you'll get the Cesium version conflict error if you follow those instructions. The fix that, you need to run `sync-dependencies` before yarn install.  Specifically:

```
cd TerriaMap
npm install -g sync-dependencies
sync-dependencies --source terriajs --from packages/terriajs/package.json
yarn install
```

**Comment by kring** [comment]
By the way, you must use `yarn` instead of `npm` in this scenario, because only yarn supports the workspaces feature. You can use npm to install a published version of terriajs, but it won't work in this development mode. To get yarn:

```
npm install -g yarn
```

**Comment by kring** [comment]
I'm closing this, but feel free to re-open (or even better, put into the gitter chat: https://gitter.im/TerriaJS/terriajs) if you have trouble.

**Comment by EricSoroos** [comment]
Thanks, I was able to get this working, on ubuntu at least.

**Comment by malnajdi** [comment]
I just want to add that i was trying to build a docker image based on my own changes to terriajs. It was always stuck at the end of 
`yarn install`
adding to the build command to be like this solved it.
`DOCKER_BUILDKIT=1 docker build .`

https://docs.docker.com/engine/reference/builder/#buildkit
