### ISSUE TITLE
How to Use Mapbox Style as Catalogue Item

### ISSUE THREAD

**Issue by quilime** [TerriaJS/TerriaMap#390]
I am having an issue including a Mapbox Map Style as a catalogue item. Note: I have set my `MapboxApi.defaultAccessToken` as instructed in `terriajs-cesium/Source/Core/MapboxApi.js`

The init config for my catalogue item is as follows:

        {
            "description" : "",
            "name" : "Mapbox",
            "type" : "mapbox-map",
            "url" : "https://api.mapbox.com/styles/v1/<mapbox-username>/cjzldyxf16qih1cm4p527ljpo/wmts?access_token=<access token>"
        }

This results in an error when pulling tiles (in the console, png's are not found, resulting in 404, 401). In the above example, I am using the "third party" Integration URL from Mapbox, which appears to be generating a WMTS server. I also tried changing the catalogue "type" to 'wmts-getCapabilities", but no avail. The URL request seems to drop the access_token variable, and results in 404, 401 errors.

I've also tried the "web" url generated by Mapbox, which uses the `mapbox://` protocol. This appears to get queried through Terria's "proxy', and doesn't seem to work, either.

Is there an example of how to properly reference a Mapbox Style as a catalogue item in TerriaJS/TerriaMap?

Many thanks.

**Comment by RussellGrew** [comment]
I believe this feature will be released into TerriaMap soon.

See https://github.com/TerriaJS/terriajs/blob/master/CHANGES.md

In the interim you can use URL templates along the lines of this example, with your access token

```
        {
          "name":"Mapbox Pirate",
          "type":"url-template",
          "url":"http://api.mapbox.com/v4/mapbox.pirates/{z}/{x}/{y}.png?access_token=XXXXXXXX",
          "isEnabled": true,
          "isShown": false,
          "opacity": 1
        },
```

I made a similar discovery and this was discussed a few weeks back https://gitter.im/TerriaJS/terriajs

**Comment by steve9164** [comment]
I'm closing this ticket as resolved. If it's not, let us know here or on our chat at https://gitter.im/TerriaJS/terriajs

**Comment by ctwhome** [comment]
> url-template

Hi, I can't manage to set the styles created with mapbox, were you able to apply the styles correctly?
```
"catalog": [
    {
      "name":"Mapbox Style",
      "type":"url-template",
      "url":"https://api.mapbox.com/styles/v1/ctwhome/ck8o3lv2037ha1inxqnzzb15s.html?fresh=true&title=copy&access_token=pk.ey...",
      "isEnabled": true,
      "isShown": false,
      "opacity":1
    },
...
```
Style map
https://api.mapbox.com/styles/v1/ctwhome/cka5fzwf412n31iqi3o6ivmvi.html?fresh=true&title=view&access_token=pk.eyJ1IjoiY3R3aG9tZSIsImEiOiJjazhpZ3ljOXUwNTR0M2VxbHhkNWl2NDEzIn0.swIehGzH7mS_TiohUmGuAg

**Comment by RussellGrew** [comment]
I have a vague memory that Mapbox may distinguish between some of their classic styles like the pirate map in my example above, and then anything new, including your custom style.

I think also that the `url-template` data type expects {x}, {y} and {z} in the link.

Perhaps https://docs.terria.io/guide/connecting-to-data/catalog-type-details/mapbox-map/ has what you are looking for?

Good luck.

**Comment by steve9164** [comment]
@ctwhome Can you get a raster tiles URL for that map? It should look something like what's described [in these Mapbox docs](https://docs.mapbox.com/api/maps/#raster-tiles). Then you can give that to TerriaJS as a `"type": "mapbox-map"` item. There's only a few parameters that really matter. See them [here](https://github.com/TerriaJS/terriajs/blob/master/lib/Models/MapboxMapCatalogItem.js#L77). Roughly like:

```
{
  "type": "mapbox-map",
  "url": "https://api.mapbox.com/v4/",
  "mapId": "mapbox.streets",
  "accessToken": "...",
}
```

**Comment by ctwhome** [comment]
@steve9164 thanks for the answer. As I understand it is not possible to get the styles created in Mapbox (mainly colors)?

**Comment by steve9164** [comment]
Maybe we need to make [Cesium's MapboxStyleImageryProvider](https://www.cesium.com/docs/cesiumjs-ref-doc/MapboxStyleImageryProvider.html) available (as type "mapbox-style" or similar) to support your map.

Probably a very easy addition. It'll be almost identical to ["mapbox-map"](https://github.com/TerriaJS/terriajs/blob/master/lib/Models/MapboxMapCatalogItem.js), just using `MapboxStyleImageryProvider` (see docs linked above) and with parameters updated to support that.

Do you want to have a go at a PR? There's some instructions on how to develop TerriaJS [here](https://docs.terria.io/guide/contributing/development-environment/).

**Comment by ctwhome** [comment]
thank you @steve9164, we are exploring the possibilities but it is sure we are going to use TerriaMaps. It can be an interesting addition for us. I can't promise anything but at least I will give it a try. Thanks again!

**Comment by ctwhome** [comment]
Hi @steve9164 I have made a pull request: https://github.com/TerriaJS/terriajs/pull/4317

But I am not able to load the map, it doesn't give any errors but it doesn't load the styles either. I am wondering if I have to call spiritedly the loaded map styles, but I don't' know how. 

Could you please take a look at the PR?
thanks!
