### ISSUE TITLE
Change Gazeteer 

### ISSUE THREAD

**Issue by KoalaGeo** [TerriaJS/TerriaMap#411]
Hi
The location search currently uses an Australian gazetteer, how do I change this? 
Cheers, 
Edd

**Comment by kring** [comment]
@KoalaGeo the location search providers are configured in TerriaMap's [index.js](https://github.com/TerriaJS/TerriaMap/blob/42bc6ec282fa57b295b1c5cec4849fd7514cb278/index.js#L69). Consider popping into our [gitter](https://gitter.im/TerriaJS/terriajs) if you have followup questions.
