### ISSUE TITLE
Mobx: Integrate rollbar error handling service

### ISSUE THREAD

**Issue by rowanwins** [TerriaJS/TerriaMap#430]
We want to start using rollbar for catching uncaught errors.

https://docs.rollbar.com/docs/react

**Comment by soyarsauce** [comment]
https://github.com/TerriaJS/handbook/issues/6

**Comment by wibily** [comment]
ticket includes investigation only

**Comment by wibily** [comment]
Pete: also consider sentry

**Comment by wibily** [comment]
Look at TerriaMap#430
