### ISSUE TITLE
 Some features missing when loading region from Vector tile layer

### ISSUE THREAD

**Issue by rulight** [TerriaJS/TerriaMap#438]
Hello, 

I'm not sure if this is an issue with Terria or from the vector tile side.
When creting regions and matching them with csv, the region features are displayed well except for the fact that a couple of polygon features (zip codes) are missing in the map.
I started playing with the csv and just left the records matching the id of the missing (not displayed) features and for some reason another feature (non related) is being displayed.. the problem is that the feature is being misssplaced and rendered incorrectly.

I'm attaching screenshots of the problem.

This is a preview of the tiles I'm using:
http://traidata.com/hilzip2010/openlayers.html
The tiles url:
http://tad3tiles.tad3.org/hilzip2010/{z}/{x}/{y}.pbf

Here is my repo with the Terria project: https://github.com/rulight/hilzip

![missing](https://user-images.githubusercontent.com/8996883/78741308-9c828280-791e-11ea-8869-554e0c3ee15f.JPG)
![only_missing_feature mismatch](https://user-images.githubusercontent.com/8996883/78741310-9d1b1900-791e-11ea-8028-7a009800daaa.JPG)

Thanks in advance.

**Comment by steve9164** [comment]
I believe I helped you solve this problem in our chat at https://gitter.im/terriajs/terriajs. The recommended way to debug this and other problems with regions not appearing or being in the wrong places is to add a `"type": "mvt"` layer using the region mapping vector tiles and compare with a region mapped layer. If they don't match the entries in `regionIdsFile` might be out of order, or the FID attribute in the geometries (in the vector tiles) doesn't start at 0 and increase by 1 for each feature, and you'll need to add your own FID that does

Please reopen or contact us again on Gitter if you still have problems getting region mapping to work.
