### ISSUE TITLE
Wrong files for deploying TerriaMap using Node.js-based web server

### ISSUE THREAD

**Issue by MoRadwan74** [TerriaJS/TerriaMap#463]
In [this section][1] of deploying TerriaMap using Node.js-based webserver, among the required files is `devserverconfig.json
`. 

Shouldn't it be `ecosystem-production.config.js` and `ecosystem.config.js`? As the executing command includes this file `ecosystem-production.config.js`

Also, to change the port from 3001 using `--port 1234` is wrong as [the docs of PM2][2] states? where `--port 1234` should be added to achieve this?

Cheers.

[1]: https://docs.terria.io/guide/deploying/deploying-terriamap/#using-the-included-nodejs-based-web-server
[2]: https://pm2.keymetrics.io/docs/usage/quick-start/

**Comment by steve9164** [comment]
Hi @MoRadwan74. Thanks for reporting this. I'll update the docs.
