### ISSUE TITLE
Cannot display timeseries on click with nc file

### ISSUE THREAD

**Issue by davidedelerma** [TerriaJS/TerriaMap#474]
We have some climate data served using ncWMS protocol (using THREDDS) and also a version using Geoserver (ncWMS plugin), we would like to display the time series graph for a specific point on click on the map. Is this feature available and is there some conf we can take as an example?

Many thanks

**Comment by rowanwins** [comment]
Closing in favour of https://github.com/TerriaJS/terriajs/issues/4665
