### ISSUE TITLE
How to change the menu?

### ISSUE THREAD

**Issue by slaboor** [TerriaJS/TerriaMap#493]
Hi, 
first: Thank you for that great application!

I used the docker image built by @icemagno #481 (thanks for that also) to build a terria map application. 
As mentioned in TerriaJS/terriajs#3806 I need to change the top menu content. In the documentation (https://docs.terria.io/guide/customizing/skinning/) there is an advice to change the UserInterface.jsx and rebuild TerriaMap. So I symlinked a changed version of UserInterface.jsx to that file via docker-compose.yml but no changes happend after restarting docker-compose.
For example I put in a new menu tab:
` <Menu>`
`         <RelatedMaps viewState={props.viewState} />`
`         <MenuItem caption="About" href="about.html" key="about-link" />`
`         <MenuItem caption="Data Catalogue" href="https://catalogue.example-url.com" key="catalogue-link" />`
` </Menu>`

Do I have to change something else to make magic happen? How do I have to rebuild TerriaMap in this case?
Thanks for any advice!

**Comment by MoRadwan74** [comment]
Did you rebuild the image after changing the code `docker-compose build --no-cache`?

**Comment by slaboor** [comment]
Thanks for the reply. Maybe I didn´t. I´ll give it a try.
