### ISSUE TITLE
Process message from parent window

### ISSUE THREAD

**Issue by mwu2018** [TerriaJS/TerriaMap#494]
The branch `next` is for the development of v8 terriajs using mobx. Currently the v8 terriajs development is focused on core functionalities and some of the non-core features are ignored. E.g. there lacks of message processing support in the current v8 terriajs. Therefore the [line](https://github.com/TerriaJS/TerriaMap/blob/a143963e7fe4e8fa896be7b2100cc97f8106eeef/index.js#L95) is commented out.

This [ticket](https://github.com/TerriaJS/nationalmap/issues/981) requires the message processing capability. Once v8 terriajs adds the message processing support, the above line should be uncommented.

**Comment by soyarsauce** [comment]
Address in fork via https://github.com/TerriaJS/terrace/issues/141
