### ISSUE TITLE
TerriaMap - release on v8/next

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/TerriaMap#536]
TerriaMap should be migrated to v8: 

- [ ] @AnaBelgun to re-organise the catalogue 
- [ ] @nf-s to migrate once catalogue is agreed (demo layers) 
- [ ] https://github.com/terriajs/saas/issues/168
- [ ] https://github.com/terriajs/terriamap/issues/532
- [ ] https://github.com/terriajs/terriamap/issues/530

**Comment by nf-s** [comment]
This is done
