### ISSUE TITLE
viewing pointcloud as 3d-tiles type in terriamap

### ISSUE THREAD

**Issue by yaryaraldebaran** [TerriaJS/TerriaMap#556]
i tried to view my pointcloud data by modifying the simple.json and add my pointcloud tileset json in the category with as 3d-tiles type. when i build and run the app, it doesn't show my pointcloud data. does terriamap support the pointcloud data as 3d-tiles or not? because i've tried using cesium js in my html and it worked well. thanks in advance

**Comment by ryo-matsuzaka** [comment]
@yaryaraldebaran 
Hi.
Is this issue is solved?
I have similar question.

**Comment by yaryaraldebaran** [comment]
> @yaryaraldebaran Hi. Is this issue is solved? I have similar question.

the error was on my data. i was converting las file into a pointcloud(.pnts file), but apparently my .las data was corrupt at the moment. then i tried to convert it again, view it in terria and it works. I suggest you to check your tileset.json path or view the data on html cesium first(my mistakes back then often happened when there's typo on the path that leads to tileset.json), CMIIW

**Comment by ryo-matsuzaka** [comment]
I suggest you to check your tileset.json path or view the data on html cesium first(my mistakes back then often happened when there's typo on the path that leads to tileset.json)

Thank you very much for quick response!
Good to here this info.
Any information about it is very informative!
Thank you very much.
