### ISSUE TITLE
Update example configs

### ISSUE THREAD

**Issue by florianm** [TerriaJS/TerriaMap#569]
Hi, I'm trying out the current main branch and found that basically all included config JSONs are broken. It would definitely help new users get up and running quickly if there were one complete and working example for each catalogue type. Edit: found https://github.com/TerriaJS/saas-catalogs-public/ with working examples.

The docs are helpful once a working example exists, but it's hard to create a working config from scratch purely from the docs.

e.g. based on a working config found through a [Github code search](https://github.com/search?q=%22type%22%3A+%22ckan-group%22&type=code) here's a working CKAN config:
```
/* Docs: https://docs.terria.io/guide/connecting-to-data/catalog-type-details/ckan-group/ */
{
    "corsDomains" : [
        "corsproxy.com",
        "catalogue.data.wa.gov.au"
    ],
    "homeCamera": {
        "west": 105,
        "south": -45,
        "east": 155,
        "north": -5
    },
    "services": [],   
    "catalog": [
        {
            "name": "WA Government Data Catalogue",
            "description": "WA public sector data.",
            "type": "ckan-group",
            "url": "https://catalogue.data.wa.gov.au/",
            "groupBy": "organization"
        }
    ]
}

```

**Comment by steve9164** [comment]
@florianm Thanks for letting us know. I've removed all of the old init files and expanded simple.json, which is written for v8.

**Comment by florianm** [comment]
Thanks, much appreciated! Happy to close this issue.
