### ISSUE TITLE
deploy terriamap on AWS

### ISSUE THREAD

**Issue by t-elisee** [TerriaJS/TerriaMap#633]
Hello,
I tried to deploy terriamap using AWS and this error message keeps pumping up!!!!! 😟
![image](https://user-images.githubusercontent.com/37068938/202492945-75e56f10-67cb-4399-b297-88bc7290294e.png)
is there any related issue concerning this error?

Thanks for the support 🙏

**Comment by steve9164** [comment]
Hi @t-elisee. Deploying to AWS using our old scripts is no longer recommended by us. We've just updated our documentation to suggest better methods of deploying TerriaMap: https://docs.terria.io/guide/deploying/

If you need the old make-package script to continue deploying to AWS using tarballs you can find it removed in this merged PR: https://github.com/TerriaJS/TerriaMap/pull/628, and restore it in a way that you see suitable.
