### ISSUE TITLE
Help me please ... How can I resolve this error? Even after reloading and reinstalling, I still get the same error here..

### ISSUE THREAD

**Issue by mrkickme101** [TerriaJS/TerriaMap#636]
![Error Feedback](https://user-images.githubusercontent.com/79897674/212552661-842d6765-d252-401a-a7d6-2e8f537ea7fd.jpg)

**Comment by AnaBelgun** [comment]
hi @mrkickme101 to be able to investigate what triggers the error, we need more information about what data have you added to the map (if any). Thank you.

**Comment by mrkickme101** [comment]
Thank u for reply me ... You can see more information https://vmcatalog.nso.go.th
