### ISSUE TITLE
On sending feedback 404 post error is showing

### ISSUE THREAD

**Issue by ayushi202** [TerriaJS/TerriaMap#638]
There is a issue with send feedback ,on sending any feedback through feedback form ,its showing 404 post request not found

**Comment by shipettos** [comment]
Hi. I have the same issue as well. Are you getting the same error?

Request has failed. Status Code: 404
Error: Request has failed. Status Code: 404
    at Function.from (webpack-internal:///./node_modules/terriajs/lib/Core/TerriaError.ts:406:25)
    at raiseError (webpack-internal:///./node_modules/terriajs/lib/Models/sendFeedback.ts:80:51)
    at eval (webpack-internal:///./node_modules/terriajs/lib/Models/sendFeedback.ts:75:5)

**Comment by nf-s** [comment]
Hi @ayushi202 and @shipettos 

Are you able to share your `serverconfig.json`? (without credentials of course!)

There is an example `feedback` configuration here

https://github.com/TerriaJS/terriajs-server/blob/master/serverconfig.json.example#L89-L101

```json5
     feedback: {
        userAgent: "TerriaBot (TerriaJS Feedback)",
        issuesUrl: "https://api.github.com/repos/TerriaJS/NationalMap-Feedback/issues",
        accessToken: "provide your GitHub access token here",
        // Add additional suported feedback parameters if required on a custom feedback form.
        // name gives the key that the parameter uses and descriptiveLabel is used as the title for the parameter in the GitHub issue description.
        additionalParameters: [
            {
                name: "organisation",
                descriptiveLabel: "Organisation"
            {
        ]
    },
```

To allow submit feedback, you will need to setup a GitHub repository and create a personal access token

**Comment by shipettos** [comment]
The only files I have are those : 
terriajs\wwwroot\test\init\serverconfig.json

and it only contains this : 

{
  "allowProxyFor": ["example.com", "csiro.au"],
  "proxyAllDomains": false
}

Also, I thought that functionality was responsible for sending a feedback email, like a "Contact Us" form to a specific email address.

**Comment by nf-s** [comment]
Hi @shipettos 

The feedback functionality currently only supports using GitHub as a "backend".
When the user submits a message, TerriaJS-server will create a GitHub issue/ticket.

If you want to remove the "Feedback" button in TerriaMap - you can remove `"feedbackUrl": "feedback",` from `wwwroot/config.json`

I am going to close this ticket, but please let me know if you have any more issues
