### ISSUE TITLE
COG support

### ISSUE THREAD

**Issue by phongnguyenai** [TerriaJS/TerriaMap#703]
Hi, can I ask which version support the cog?

In this link: https://docs.terria.io/guide/connecting-to-data/catalog-type-details/cog/

I found that cog is one of the supported data type. But I don't know why the latest version doesn't support it.

**Comment by ljowen** [comment]
Hi @phongnguyenai 
Cog support was added in `8.7.8` you should be able to just bump your version to that in `package.json`. We'll be releasing an updated TerriaMap soon

**Comment by na9da** [comment]
@phongnguyenai - COG support is now available in the latest `main`. 

You can add COG url via `Upload data > Add web data` or via catalog file. 

Here's  an example catalog definition:
```json
{
          "name": "USGS Elevation",
          "description": "EPSG:4269",
          "type": "cog",
          "url": "https://prd-tnm.s3.amazonaws.com/StagedProducts/Elevation/13/TIFF/current/n06e162/USGS_13_n06e162.tif"
}
```

More documentation [available here](https://docs.terria.io/guide/connecting-to-data/catalog-type-details/cog/).

Closing this issue for now. Let us know if you have any more questions.
