### ISSUE TITLE
npm install fails on terriajs#webpack

### ISSUE THREAD

**Issue by DanielBaird** [TerriaJS/TerriaMap#9]
The error is "fatal: ambiguous argument 'webpack': unknown revision or path not in the working tree" which I think is because the terriajs dependency in `package.json` is asking for the webpack branch, that doesn't exist now.

I'm trialling a fix switching the branch to master.  I'll pullreq that if it works.

**Comment by kring** [comment]
Yes, I believe that's the right fix for now.  Things are a bit in flux at the moment with the switch to webpack, so thanks for your patience!
